#!/usr/bin/env python3
"""The global record board: a small HTTP service over one SQLite file.

The game itself is static - index.html plus css/, js/ and assets/ - and stays that way.
This is the one optional moving part, and it is deliberately small: Python's standard
library, no framework, no dependencies, one file on disk you can copy to back up.

    python3 server/scores.py                       # 127.0.0.1:8011, db at ./zrace.db
    python3 server/scores.py --port 8011 --db /var/lib/zrace/zrace.db

nginx puts it behind /api/ on the same origin as the game; see tools/deploy.sh. It binds
to localhost by default and should stay there - it has no authentication, because there
is nothing here worth authenticating and a login on a fan racing game is a worse idea
than an honest board.

Routes
    GET  /api/health             {ok, tracks, records}
    GET  /api/records            every circuit's board, one round trip
    GET  /api/records/<track>    one circuit's board
    POST /api/records            {track, name, car, carName, ms} -> {rank, board}

What stops people making times up
    Nothing proves a lap was driven. But server/floors.json, generated by
    tools/lap_floors.mjs, holds the fastest lap each car could physically manage on each
    circuit - cornering, braking and accelerating at the limit the whole way round - and
    anything quicker than that did not happen, so it is refused. Submissions are also
    rate limited per address. Between them that keeps out the casual `curl` of a
    twelve-second Monaco lap, which is the realistic threat to a board like this.
"""

import argparse
import json
import os
import re
import sqlite3
import sys
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

TOP = 25                 # rows served per circuit
MAX_ROWS_PER_TRACK = 5000
MAX_NAME = 14
MAX_LAP_MS = 30 * 60 * 1000
MAX_BODY = 4096

# per address, over a sliding window
WRITE_LIMIT, WRITE_WINDOW = 30, 600
READ_LIMIT, READ_WINDOW = 240, 60

CONTROL = re.compile(r"[\x00-\x1f\x7f]")
# The client escapes on render, which is where XSS is actually stopped. Angle
# brackets come out here as well so anything else that ever reads this database -
# an export, a dashboard, a log line - inherits a name that cannot pass as markup.
ANGLE = re.compile(r"[<>]")

SCHEMA = """
CREATE TABLE IF NOT EXISTS records (
  track    TEXT    NOT NULL,
  name     TEXT    NOT NULL,
  car      TEXT    NOT NULL,
  car_name TEXT    NOT NULL,
  ms       INTEGER NOT NULL,
  at       INTEGER NOT NULL,
  PRIMARY KEY (track, name, car)
);
CREATE INDEX IF NOT EXISTS records_board ON records (track, ms);
"""


class Store:
    """One connection behind one lock.

    A board takes a handful of writes a minute at the very most, so there is nothing to
    gain from a pool and something to lose from the complexity. WAL is on so reads never
    wait behind the writer.
    """

    def __init__(self, path):
        first = not os.path.exists(path)
        self.db = sqlite3.connect(path, check_same_thread=False)
        self.db.row_factory = sqlite3.Row
        self.db.execute("PRAGMA journal_mode=WAL")
        self.db.execute("PRAGMA synchronous=NORMAL")
        self.db.executescript(SCHEMA)
        self.db.commit()
        self.lock = threading.Lock()
        if first:
            log(f"created {path}")

    def board(self, track, limit=TOP):
        with self.lock:
            rows = self.db.execute(
                "SELECT name, car, car_name, ms, at FROM records"
                " WHERE track = ? ORDER BY ms ASC LIMIT ?",
                (track, limit),
            ).fetchall()
        return [
            {"name": r["name"], "carId": r["car"], "car": r["car_name"],
             "ms": r["ms"], "at": r["at"]}
            for r in rows
        ]

    def boards(self, tracks):
        return {t: self.board(t) for t in tracks}

    def submit(self, track, name, car, car_name, ms):
        """Upsert the driver's best in that car, and return their rank, or 0 if the row
        they already hold is faster than what they just sent."""
        now = int(time.time() * 1000)
        with self.lock:
            cur = self.db.execute(
                "INSERT INTO records (track, name, car, car_name, ms, at)"
                " VALUES (?, ?, ?, ?, ?, ?)"
                " ON CONFLICT(track, name, car) DO UPDATE SET"
                "   ms = excluded.ms, at = excluded.at, car_name = excluded.car_name"
                " WHERE excluded.ms < records.ms",
                (track, name, car, car_name, ms, now),
            )
            improved = cur.rowcount > 0
            # keep a runaway board from growing without bound
            self.db.execute(
                "DELETE FROM records WHERE rowid IN ("
                "  SELECT rowid FROM records WHERE track = ?"
                "  ORDER BY ms ASC LIMIT -1 OFFSET ?)",
                (track, MAX_ROWS_PER_TRACK),
            )
            self.db.commit()
            rank = self.db.execute(
                "SELECT COUNT(*) + 1 FROM records WHERE track = ? AND ms < ?"
                " AND NOT (name = ? AND car = ?)",
                (track, ms, name, car),
            ).fetchone()[0]
        return (rank if rank <= TOP else 0) if improved else 0

    def count(self):
        with self.lock:
            return self.db.execute("SELECT COUNT(*) FROM records").fetchone()[0]


class RateLimit:
    """Sliding window per address. In memory, so it resets on restart - which is fine,
    because it is a speed bump for abuse, not a security boundary."""

    def __init__(self):
        self.hits = {}
        self.lock = threading.Lock()

    def allow(self, key, limit, window):
        now = time.monotonic()
        with self.lock:
            seen = [t for t in self.hits.get(key, ()) if now - t < window]
            if len(seen) >= limit:
                self.hits[key] = seen
                return False
            seen.append(now)
            self.hits[key] = seen
            if len(self.hits) > 10000:                  # cheap sweep
                self.hits = {k: v for k, v in self.hits.items() if v and now - v[-1] < window}
        return True


def clean_name(raw):
    name = ANGLE.sub("", CONTROL.sub("", str(raw or "")))
    name = " ".join(name.split())[:MAX_NAME].strip()
    return name or "Player"


def log(msg):
    print(f"[zrace-scores] {msg}", flush=True)


class Handler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"
    server_version = "zrace-scores"

    # ------------------------------------------------------------------ plumbing
    def send_json(self, obj, status=200):
        body = json.dumps(obj).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        # The board is public and the service holds no cookies or credentials, so there
        # is nothing a cross-origin caller could do that `curl` could not. Allowing it
        # means the game can be served from a different port while you develop.
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def fail(self, status, reason):
        self.send_json({"error": reason}, status)

    def client(self):
        # behind nginx every connection comes from 127.0.0.1, so trust the proxy's header
        fwd = self.headers.get("X-Forwarded-For", "")
        return fwd.split(",")[0].strip() if fwd else self.client_address[0]

    def log_message(self, fmt, *args):
        pass                                    # journald gets our own lines, not these

    def do_OPTIONS(self):
        self.send_json({}, 204)

    # --------------------------------------------------------------------- routes
    def do_GET(self):
        store, floors, limiter = self.server.store, self.server.floors, self.server.limiter
        path = self.path.split("?")[0].rstrip("/")

        if not limiter.allow(("r", self.client()), READ_LIMIT, READ_WINDOW):
            return self.fail(429, "slow down")

        if path == "/api/health":
            return self.send_json({"ok": True, "tracks": sorted(floors), "records": store.count()})
        if path == "/api/records":
            return self.send_json({"boards": store.boards(sorted(floors)), "top": TOP})
        if path.startswith("/api/records/"):
            track = path[len("/api/records/"):]
            if track not in floors:
                return self.fail(404, "no such circuit")
            return self.send_json({"track": track, "rows": store.board(track), "top": TOP})
        return self.fail(404, "not found")

    do_HEAD = do_GET

    def do_POST(self):
        store, floors, limiter = self.server.store, self.server.floors, self.server.limiter
        if self.path.split("?")[0].rstrip("/") != "/api/records":
            return self.fail(404, "not found")

        if not limiter.allow(("w", self.client()), WRITE_LIMIT, WRITE_WINDOW):
            return self.fail(429, "slow down")

        try:
            length = int(self.headers.get("Content-Length") or 0)
        except ValueError:
            return self.fail(400, "bad length")
        if length <= 0 or length > MAX_BODY:
            return self.fail(400, "bad length")
        try:
            body = json.loads(self.rfile.read(length))
            if not isinstance(body, dict):
                raise ValueError
        except (ValueError, json.JSONDecodeError):
            return self.fail(400, "bad json")

        track = str(body.get("track", ""))
        car = str(body.get("car", ""))
        if track not in floors:
            return self.fail(400, "no such circuit")
        if car not in floors[track]:
            return self.fail(400, "no such car")
        try:
            ms = int(body.get("ms"))
        except (TypeError, ValueError):
            return self.fail(400, "bad lap time")
        if ms <= 0 or ms > MAX_LAP_MS:
            return self.fail(400, "bad lap time")

        floor = floors[track][car]
        if ms < floor:
            log(f"refused {ms}ms for {car} at {track} from {self.client()} (floor {floor}ms)")
            return self.fail(422, "that lap is faster than the car can go")

        name = clean_name(body.get("name"))
        car_name = CONTROL.sub("", str(body.get("carName", car)))[:40] or car
        rank = store.submit(track, name, car, car_name, ms)
        self.send_json({"rank": rank, "rows": store.board(track), "top": TOP})


def main(argv=None):
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser(description="ZRace global record board")
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=8011)
    ap.add_argument("--db", default=os.environ.get("ZRACE_DB", "zrace.db"))
    ap.add_argument("--floors", default=os.path.join(here, "floors.json"))
    args = ap.parse_args(argv)

    try:
        with open(args.floors, encoding="utf-8") as fh:
            floors = json.load(fh)["floors"]
    except (OSError, KeyError, json.JSONDecodeError) as err:
        sys.exit(f"cannot read lap floors from {args.floors}: {err}\n"
                 f"generate them with: node tools/lap_floors.mjs")

    db_dir = os.path.dirname(os.path.abspath(args.db))
    if db_dir:
        os.makedirs(db_dir, exist_ok=True)

    httpd = ThreadingHTTPServer((args.host, args.port), Handler)
    httpd.daemon_threads = True
    httpd.store = Store(args.db)
    httpd.floors = floors
    httpd.limiter = RateLimit()
    log(f"listening on {args.host}:{args.port}, db {os.path.abspath(args.db)}, "
        f"{len(floors)} circuits, {httpd.store.count()} records")
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        log("stopping")
    finally:
        httpd.server_close()


if __name__ == "__main__":
    main()
